[package]
name = "liner"
version = "0.1.0"
edition = "2021"
crate-type = ["cdylib"]      # Creates dynamic lib

[dependencies]
redis = "0.26.1"
rayon = "1.10"
libc = "0.2"

[features]
liner_debug = []

[profile.release]
panic = "abort"
codegen-units = 1
lto = "fat"
