pub const WRITE_BUFFER_CAPASITY: usize = 8192;
pub const READ_BUFFER_CAPASITY: usize = 8192;
pub const EPOLL_LISTEN_EVENTS_COUNT: usize = 128;
pub const CHECK_AVAILABLE_STREAM_TIMEOUT_MS: u64 = 10*1000; //10sec
pub const WRITE_MESS_DELAY_MS: u64 = 1;